# Generated by Django 4.2 on 2023-04-08 09:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.contrib import auth
from django.contrib.auth import models as auth_models
from btell_main.util import user_util


def create_superuser_forward(apps, schema_editor):
    User = auth.get_user_model()
    db_alias = schema_editor.connection.alias
    admin, _created = User.objects.using(db_alias).get_or_create(
        username='admin',
        email='admin@site.local',
        first_name='Admini',
        last_name='Strator'
    )  # type: ignore
    if isinstance(admin, User):
        admin: auth_models.User = admin
        generated_password = user_util.generate_random_password(
            settings.MIN_PASSWORD_LENGTH)
        if settings.DEBUG:
            generated_password = "admin"
        admin.set_password(generated_password)
        admin.is_staff = True
        admin.is_superuser = True
        admin.save()
        print(
            f"\n\n  - Generated admin user 'admin' with password '{generated_password}")
        print('  - Please change this password at your earliest convenience.\n\n')
    else:
        raise TypeError(
            f"Was expecting the default user model, not '{type(User)}'.")


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('default_theme', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(default='DEFAULT',
                 max_length=100, verbose_name='website_theme')),
                ('user', models.OneToOneField(
                    on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RunPython(create_superuser_forward)
    ]
