# Generated by Django 4.2 on 2023-04-08 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('btell_main', '0002_comment_tags_story'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='draft',
            field=models.BooleanField(default=True),
        ),
    ]
