# Generated by Django 4.2 on 2023-04-08 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('btell_main', '0003_story_draft'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='cover_image_file',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='cover_image_source',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
