# Generated by Django 4.2 on 2023-05-13 14:27

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('btell_main', '0004_story_cover_image_file_story_cover_image_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('published', models.DateTimeField(null=True)),
                ('last_update', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('chapter_image', models.CharField(max_length=32, null=True)),
                ('chapter_image_source', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StoryReader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('current_chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='btell_main.chapter')),
            ],
        ),
        migrations.AlterField(
            model_name='story',
            name='published',
            field=models.DateTimeField(null=True),
        ),
        migrations.CreateModel(
            name='StoryReaderVars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variable_name', models.CharField(max_length=50)),
                ('variable_value', models.SmallIntegerField(default=0)),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='btell_main.storyreader')),
            ],
        ),
        migrations.AddField(
            model_name='storyreader',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='btell_main.story'),
        ),
        migrations.AddField(
            model_name='storyreader',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ChapterLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=50)),
                ('condition', models.CharField(max_length=500, null=True)),
                ('action', models.CharField(max_length=500, null=True)),
                ('from_chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='btell_main.chapter')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='btell_main.story')),
                ('to_chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='btell_main.chapter')),
            ],
        ),
        migrations.AddField(
            model_name='chapter',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='btell_main.story'),
        ),
    ]
