# Generated by Django 4.2 on 2023-05-28 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('btell_main', '0005_chapter_storyreader_alter_story_published_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='draft',
        ),
    ]
